// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO (codelab user): Replace with your Firebase credentials

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByEG55ykg2IooI_FVxP7ygayNVzQrUbsg',
    appId: '1:978421415158:web:9c62ecd975a34f318180d7',
    messagingSenderId: '978421415158',
    projectId: 'auth-f3e4d',
    authDomain: 'auth-f3e4d.firebaseapp.com',
    storageBucket: 'auth-f3e4d.firebasestorage.app',
  );

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxaef07o1pGg9vYIKe69Xs6kDXH73_8ag',
    appId: '1:978421415158:android:b81985c42175c1818180d7',
    messagingSenderId: '978421415158',
    projectId: 'auth-f3e4d',
    storageBucket: 'auth-f3e4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMCmzP-HRMmwoADVYQmRrnoCTh3bQs2-o',
    appId: '1:978421415158:ios:a32804394e1cbe048180d7',
    messagingSenderId: '978421415158',
    projectId: 'auth-f3e4d',
    storageBucket: 'auth-f3e4d.firebasestorage.app',
    iosClientId: '978421415158-j9motbtvm58d9f6586bkhpl4vpbgm0lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMCmzP-HRMmwoADVYQmRrnoCTh3bQs2-o',
    appId: '1:978421415158:ios:a32804394e1cbe048180d7',
    messagingSenderId: '978421415158',
    projectId: 'auth-f3e4d',
    storageBucket: 'auth-f3e4d.firebasestorage.app',
    iosClientId: '978421415158-j9motbtvm58d9f6586bkhpl4vpbgm0lg.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

}